name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install X11 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxkbcommon-x11-dev libxcb-xkb-dev libxcb1-dev libxcb-render0-dev libxcb-icccm4-dev libxcb-image0-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Go Version
        run: go version

      - name: Tidy modules
        run: make tidy

      - name: install golang ci lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run linting
        run: make lint

  test:
    runs-on: ubuntu-latest
    env:
      COVERAGE_THRESHOLD: 80
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "gcat CI"
          git config --global user.email "ci@timsexperiments.foo"

      - name: Install X11 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxkbcommon-x11-dev libxcb-xkb-dev libxcb1-dev libxcb-render0-dev libxcb-icccm4-dev libxcb-image0-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Go Version
        run: go version

      - name: Tidy modules
        run: make tidy

      - name: Run tests and generate coverage
        run: make coverage

      - name: Check project coverage threshold (warning only)
        run: |
          COVERAGE=$(go tool cover -func=coverage/coverage.out | grep total: | awk '{print $3}' | sed 's/%//')
          echo "Total coverage is: ${COVERAGE}%"
          if (( $(echo "$COVERAGE < $COVERAGE_THRESHOLD" | bc -l) )); then
            echo "WARNING: Coverage ($COVERAGE%) is below the threshold of ${COVERAGE_THRESHOLD}%."
          else
            echo "Coverage ($COVERAGE%) meets the threshold of ${COVERAGE_THRESHOLD}%."
          fi

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install X11 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-dev libxkbcommon-x11-dev libxcb-xkb-dev libxcb1-dev libxcb-render0-dev libxcb-icccm4-dev libxcb-image0-dev xorg-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.6"

      - name: Go Version
        run: go version

      - name: Tidy modules
        run: make tidy

      - name: Build the application
        run: make build
