name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*.*.*" # Matches standard versions
      - "v*.*.*-*" # Matches prerelease versions
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.6"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
